# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a2655fe7010932a9dc3ef45767d7738427c66d1b97cb62d440fcee74c05216fe778a38bb76a597f64edd69f38e9fe83ac0dc92fc1a268b039eca3fac44a558f

test:
  secret_key_base: ea9a1f6984fc7ee3384cce5578767e87966eaf45c0546f02e50b3b13fa7020af4f441734d1ffb5df8337a078da87153be58d508b0e8086732a18a14c91bb5444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
